<a href="https://colab.research.google.com/github/ifrahsaleem/Genome-Pairwise-Alignment/blob/master/Pairwise_Alignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:
!ls
file = input("Enter file name: ")
file = open(file)

read_file = file.read()
list_file = read_file.split()

seq1 = list_file[0]
seq2 = list_file[1]
mismatch_score = int(input("Enter the mismatch score: "))
gap_penalty = int(input("Enter the gap penalty: "))
match_score =  int(input("Enter the match score: "))
extend_penalty = gap_penalty 

seq1_list = list(seq1)
seq2_list = list(seq2)

#alignments = pairwise2.align.globalms(seq1, seq2, match_score, mismatch_score, gap_penalty, extend_penalty)

#for a in alignments: 
  #print(format_alignment(*a))
  
def match(alpha, beta):
    if alpha == beta:
        return match_score
    else:
        return mismatch_score
      
num_rows = len(seq2) + 1
num_cols = len(seq1) + 1
matrix = np.zeros(shape=(num_rows, num_cols), dtype=np.int)
str_matrix = np.zeros(shape=(num_rows, num_cols), dtype=str)

matrix[0][0] = 0
for i in range(1, num_rows):
    matrix[i][0] = matrix[i-1][0] + gap_penalty
    str_matrix[i][0] = '↑'

for j in range(1, num_cols):
    matrix[0][j] = matrix[0][j-1] + gap_penalty
    str_matrix[0][j] = '←'

seq1_list = len(list(seq1))
seq2_list = len(list(seq2))
align1 = []
align2 = []
align3 = []

str_matrix[0][0] = 0
list1 = list(range(1,len(seq2)+1))
while list1 != []:
  for i in range(1,len(seq1)+1):
        j = list1[0]
        diagonal = matrix[j - 1][i - 1] + match(seq1[i-1],seq2[j-1])
        up = matrix[j][i-1] + gap_penalty
        left = matrix[j-1][i] + gap_penalty
        max_pointer =max(diagonal, up, left)
        matrix[j][i] =  max_pointer 
        if max_pointer == diagonal:
            str_matrix[j][i] = '↖'
        elif max_pointer == up:
            str_matrix[j][i] = '↑'
        else: 
            str_matrix[j][i] = '←'
  del list1[0]

print('\n')
print('\n')
print(matrix)
print('\n')
print(str_matrix)

score = matrix[-1][-1]

print("Score: ", score)
print('\n')
                                                                                                         
i,j = seq2_list, seq1_list                                                     
while i > 0 or j > 0: 
        score_current = matrix[i][j]
        score_diagonal = matrix[i-1][j-1]
        score_up = matrix[i-1][j]
        score_left = matrix[i][j-1]
        numlist = []
        symb = []
      
        if gap_penalty == score_current - score_up:
          numlist.append(score_up)
          
        if gap_penalty == score_current - score_left:
          numlist.append(score_left)
          
        if match_score == score_current - score_diagonal:
          numlist.append(score_diagonal)
          
        if mismatch_score == score_current - score_diagonal:
          numlist.append(score_diagonal)
          
        maxnum = max(numlist)      
        if maxnum == score_diagonal:
          align1.append(seq1[j-1])
          align2.append(seq2[i-1])
          align3.append(seq2[i-1])
          i -= 1
          j -= 1  
          
        elif maxnum == score_up:
          align1.append('-')
          align2.append(seq2[i-1])
          align3.append(seq2[i-1])
          i -= 1
         
        else: 
          align1.append(seq1[j-1])
          align2.append('-')
          align3.append('-')
          j -= 1   
          
while j > 0:
        align1.append(seq1[j-1])
        align2.append('-')
        align3.append('-')
        j -= 1
while i > 0:
        align1.append('-')
        align2.append(seq2[i-1])
        align3.append(seq2[i-1])
        i -= 1
      
(align1.reverse())
(align2.reverse())
(align3.reverse())

symb = []

for a in align1:
  b = align3[0]
  if a==b:
    symb.append("|")
  elif a == "-":
    symb.append(" ")
  elif b == "-":
    symb.append(" ")
  else:
    symb.append(".")
  del align3[0]
          
a = ("".join(symb)) 
print(*align1, sep='')
print(a)
print(*align2, sep='')
                
with open("drive/My Drive/SequenceAlignment.txt", "w") as new_file:
    new_file.write("Match Score: %s \n " % match_score)
    new_file.write('\n')
    new_file.write("Mismatch Score: %s \n " % mismatch_score)
    new_file.write('\n')
    new_file.write("Gap Penalty: %s " % gap_penalty)
    new_file.write('\n')
    new_file.write('\n')
    new_file.write("Score: %s " % score)
    new_file.write('\n')
    new_file.write('\n')
    new_file.write('\n')
    string1 = ''
    string2 = ''
    for x in align1:
        string1 += x 
    new_file.write(string1)
    new_file.write('\n')
    new_file.write(a)
    new_file.write('\n')
    for x in align2:
        string2 += x 
    new_file.write(string2)
    new_file.write('\n')
    new_file.write('\n') 
    np.savetxt(new_file, matrix, fmt='%-4d', delimiter = '|', newline='\n')
    new_file.write('\n')
    np.savetxt(new_file, str_matrix, fmt='%s', delimiter = '|', newline = '\n')    
new_file.close()

drive  sample_data
Enter file name: drive/My Drive/test_input5.txt
Enter the mismatch score: -7
Enter the gap penalty: -3
Enter the match score: 8




[[  0  -3  -6  -9 -12 -15 -18 -21 -24 -27 -30 -33 -36 -39 -42 -45 -48]
 [ -3   8   5   2  -1  -4  -7 -10 -13 -16 -19 -22 -25 -28 -31 -34 -37]
 [ -6   5  16  13  10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26]
 [ -9   2  13  10  21  18  15  12   9   6   3   0  -3  -6  -9 -12 -15]
 [-12  -1  10   7  18  15  12   9  20  17  14  11   8   5   2  -1  -4]
 [-15  -4   7   4  15  12   9   6  17  28  25  22  19  16  13  10   7]
 [-18  -7   4   1  12   9   6   3  14  25  36  33  30  27  24  21  18]
 [-21 -10   1  -2   9  20  17  14  11  22  33  44  41  38  35  32  29]
 [-24 -13  -2  -5   6  17  14  11   8  19  30  41  38  35  32  29  26]
 [-27 -16  -5   6   3  14  11   8   5  16  27  38  35  32  29  26  23]
 [-30 -19  -8   3  14  11   8   5  16  13  24  35  32  43  40  37  34]
 [-33 -22 -11   0  11  22  19  16  13  10  21  32  43  40  37  34  4